# theme configuration
[theme]
theme = "nord-dark"
[theme.overrides]
# separator
#separator = ""
#separator_fg = "#101010"
#separator_bg = "#a6a5a4"
# idle
#idle_fg = "#101010"
#idle_bg = "#a6a5a4"
# good 
#good_fg = "#101010"
#good_bg = "#a6a5a4"
# warning
#warning_fg = "#ea802e"
#warning_bg = "#a6a5a4"
# critical
#critical_fg = "#ea2e3b"
#critical_bg = "#a6a5a4"
# alternating tint
#alternating_tint_fg = "#101010"
#alternating_tint_bg = "#a6a5a4"

# user@host
[[block]]
block = "custom"
command = "echo $(whoami)@$(cat /etc/hostname)"
interval = "once" 

# ip addr
[[block]]
block = "external_ip"
format = " $ip "

# cpu usage
[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 65
critical_cpu = 90
format = "cpu $utilization"

# ram usage
[[block]]
block = "memory"
format = "mem $mem_used_percents"

# available space
[[block]]
block = "disk_space"
path = "/"
info_type = "used"
interval = 20
warning = 70
alert = 90
format = "disk $percentage"

# current time
[[block]]
block = "time"
interval = 5
format = "$timestamp.datetime(f:'%a %d/%m %R') "
